// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CourseStatus.
const (
	Closed   CourseStatus = "closed"
	Deleted  CourseStatus = "deleted"
	Expired  CourseStatus = "expired"
	Open     CourseStatus = "open"
	Personal CourseStatus = "personal"
)

// Defines values for UserRole.
const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleLain    UserRole = "Lain"
	UserRoleMember  UserRole = "member"
	UserRoleMentor  UserRole = "mentor"
	UserRoleTeacher UserRole = "teacher"
)

// Defines values for GetUsersParamsRole.
const (
	GetUsersParamsRoleAdmin   GetUsersParamsRole = "admin"
	GetUsersParamsRoleLain    GetUsersParamsRole = "Lain"
	GetUsersParamsRoleMember  GetUsersParamsRole = "member"
	GetUsersParamsRoleMentor  GetUsersParamsRole = "mentor"
	GetUsersParamsRoleTeacher GetUsersParamsRole = "teacher"
)

// Course defines model for Course.
type Course struct {
	AuthorId      *int          `json:"author_id,omitempty"`
	Category      *[]string     `json:"category,omitempty"`
	CourseImageId *string       `json:"course_image_id,omitempty"`
	CreatedAt     *time.Time    `json:"createdAt,omitempty"`
	Description   *string       `json:"description,omitempty"`
	EndDate       *time.Time    `json:"endDate,omitempty"`
	Id            *int32        `json:"id,omitempty"`
	Price         *float32      `json:"price,omitempty"`
	StartDate     *time.Time    `json:"startDate,omitempty"`
	Status        *CourseStatus `json:"status,omitempty"`
	Title         *string       `json:"title,omitempty"`
	UpdatedAt     *time.Time    `json:"updatedAt,omitempty"`
}

// CourseStatus defines model for Course.Status.
type CourseStatus string

// Courses defines model for Courses.
type Courses = []Course

// InternalServiceError defines model for InternalServiceError.
type InternalServiceError struct {
	Code    *int         `json:"code,omitempty"`
	Message *interface{} `json:"message,omitempty"`
}

// Playlist defines model for Playlist.
type Playlist struct {
	AuthorId    int        `json:"author_id"`
	CoursesIds  *[]int     `json:"courses_ids,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	ImageId     *string    `json:"image_id,omitempty"`
	Title       string     `json:"title"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

// Playlists defines model for Playlists.
type Playlists = []Playlist

// User defines model for User.
type User struct {
	AvatarId    string     `json:"avatar_id"`
	Description *string    `json:"description,omitempty"`
	Email       string     `json:"email"`
	Id          *int64     `json:"id,omitempty"`
	Login       string     `json:"login"`
	Password    *string    `json:"password,omitempty"`
	Role        []UserRole `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserSignIn defines model for UserSignIn.
type UserSignIn struct {
	Email    *string `json:"email,omitempty"`
	Login    *string `json:"login,omitempty"`
	Password *string `json:"password,omitempty"`
}

// UserSignUp defines model for UserSignUp.
type UserSignUp struct {
	Email        *string `json:"email,omitempty"`
	Login        *string `json:"login,omitempty"`
	Notification *bool   `json:"notification,omitempty"`
	Password     *string `json:"password,omitempty"`
}

// Users List of user object
type Users = []User

// UploadCourseImageMultipartBody defines parameters for UploadCourseImage.
type UploadCourseImageMultipartBody map[string]interface{}

// GetCoursesParams defines parameters for GetCourses.
type GetCoursesParams struct {
	// Limit Параметр для получения определенное количество курсов
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Параметр для получения определенного количества курсов через offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// OrderBy Параметр для сортировки курсов по указанному полю и методу сортировки
	OrderBy *string `form:"orderBy,omitempty" json:"orderBy,omitempty"`
}

// GetPlaylistsParams defines parameters for GetPlaylists.
type GetPlaylistsParams struct {
	// Limit Параметр для получения определенное количество курсов
	Limit     *int      `form:"limit,omitempty" json:"limit,omitempty"`
	Author    *[]string `form:"author,omitempty" json:"author,omitempty"`
	CreatedAt *string   `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Status    *[]string `form:"status,omitempty" json:"status,omitempty"`
	Title     *string   `form:"title,omitempty" json:"title,omitempty"`

	// OrderBy Параметр для сортировки курсов по указанному полю и методу сортировки
	OrderBy *string `form:"orderBy,omitempty" json:"orderBy,omitempty"`
}

// UploadPlaylistImageMultipartBody defines parameters for UploadPlaylistImage.
type UploadPlaylistImageMultipartBody = string

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Limit Параметр для получения определенное количество курсов
	Limit *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Role  *[]GetUsersParamsRole `form:"role,omitempty" json:"role,omitempty"`

	// OrderBy Параметр для сортировки курсов по указанному полю и методу сортировки
	OrderBy *string `form:"orderBy,omitempty" json:"orderBy,omitempty"`
}

// GetUsersParamsRole defines parameters for GetUsers.
type GetUsersParamsRole string

// UploadUserAvatarMultipartBody defines parameters for UploadUserAvatar.
type UploadUserAvatarMultipartBody = string

// UploadCourseImageMultipartRequestBody defines body for UploadCourseImage for multipart/form-data ContentType.
type UploadCourseImageMultipartRequestBody UploadCourseImageMultipartBody

// CreatePlaylistJSONRequestBody defines body for CreatePlaylist for application/json ContentType.
type CreatePlaylistJSONRequestBody = Playlist

// UploadPlaylistImageMultipartRequestBody defines body for UploadPlaylistImage for multipart/form-data ContentType.
type UploadPlaylistImageMultipartRequestBody = UploadPlaylistImageMultipartBody

// UploadUserAvatarMultipartRequestBody defines body for UploadUserAvatar for multipart/form-data ContentType.
type UploadUserAvatarMultipartRequestBody = UploadUserAvatarMultipartBody

// UserSignInJSONRequestBody defines body for UserSignIn for application/json ContentType.
type UserSignInJSONRequestBody = UserSignIn

// UserSignUpJSONRequestBody defines body for UserSignUp for application/json ContentType.
type UserSignUpJSONRequestBody = UserSignUp

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload image
	// (POST /course/image/{user_id})
	UploadCourseImage(w http.ResponseWriter, r *http.Request, userId int)
	// Create course
	// (POST /course/new)
	CreateCourse(w http.ResponseWriter, r *http.Request)
	// Delete course
	// (DELETE /course/{id})
	DeleteCourse(w http.ResponseWriter, r *http.Request, id int)
	// Get course by id
	// (GET /course/{id})
	GetCourseById(w http.ResponseWriter, r *http.Request, id int)
	// Update course
	// (PUT /course/{id})
	UpdateCourse(w http.ResponseWriter, r *http.Request, id int)
	// List all courses
	// (GET /courses)
	GetCourses(w http.ResponseWriter, r *http.Request, params GetCoursesParams)
	// List all playlists
	// (GET /playlists)
	GetPlaylists(w http.ResponseWriter, r *http.Request, params GetPlaylistsParams)
	// Create playlist
	// (POST /playlists/new)
	CreatePlaylist(w http.ResponseWriter, r *http.Request)
	// Delete playlist
	// (DELETE /playlists/{id})
	DeletePlaylist(w http.ResponseWriter, r *http.Request, id int)
	// Get playlist by id
	// (GET /playlists/{id})
	GetPlaylistById(w http.ResponseWriter, r *http.Request, id int)
	// Update playlist
	// (PUT /playlists/{id})
	UpdatePlaylist(w http.ResponseWriter, r *http.Request, id int)
	// Upload image to playlist
	// (POST /playlists/{playlist_id}/image)
	UploadPlaylistImage(w http.ResponseWriter, r *http.Request, playlistId int)
	// pong
	// (GET /pong)
	Pong(w http.ResponseWriter, r *http.Request)
	// Delete user
	// (DELETE /user/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id int)
	// Get user by id
	// (GET /user/{id})
	GetUserById(w http.ResponseWriter, r *http.Request, id int)
	// Update user
	// (PUT /user/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id int)
	// List all users
	// (GET /users)
	GetUsers(w http.ResponseWriter, r *http.Request, params GetUsersParams)
	// Upload avatar
	// (POST /users/avatar)
	UploadUserAvatar(w http.ResponseWriter, r *http.Request)
	// Authorize user
	// (POST /users/sign_in)
	UserSignIn(w http.ResponseWriter, r *http.Request)
	// Create user
	// (POST /users/sign_up)
	UserSignUp(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Upload image
// (POST /course/image/{user_id})
func (_ Unimplemented) UploadCourseImage(w http.ResponseWriter, r *http.Request, userId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create course
// (POST /course/new)
func (_ Unimplemented) CreateCourse(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete course
// (DELETE /course/{id})
func (_ Unimplemented) DeleteCourse(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get course by id
// (GET /course/{id})
func (_ Unimplemented) GetCourseById(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update course
// (PUT /course/{id})
func (_ Unimplemented) UpdateCourse(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all courses
// (GET /courses)
func (_ Unimplemented) GetCourses(w http.ResponseWriter, r *http.Request, params GetCoursesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all playlists
// (GET /playlists)
func (_ Unimplemented) GetPlaylists(w http.ResponseWriter, r *http.Request, params GetPlaylistsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create playlist
// (POST /playlists/new)
func (_ Unimplemented) CreatePlaylist(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete playlist
// (DELETE /playlists/{id})
func (_ Unimplemented) DeletePlaylist(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get playlist by id
// (GET /playlists/{id})
func (_ Unimplemented) GetPlaylistById(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update playlist
// (PUT /playlists/{id})
func (_ Unimplemented) UpdatePlaylist(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload image to playlist
// (POST /playlists/{playlist_id}/image)
func (_ Unimplemented) UploadPlaylistImage(w http.ResponseWriter, r *http.Request, playlistId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// pong
// (GET /pong)
func (_ Unimplemented) Pong(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete user
// (DELETE /user/{id})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user by id
// (GET /user/{id})
func (_ Unimplemented) GetUserById(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update user
// (PUT /user/{id})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all users
// (GET /users)
func (_ Unimplemented) GetUsers(w http.ResponseWriter, r *http.Request, params GetUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload avatar
// (POST /users/avatar)
func (_ Unimplemented) UploadUserAvatar(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authorize user
// (POST /users/sign_in)
func (_ Unimplemented) UserSignIn(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create user
// (POST /users/sign_up)
func (_ Unimplemented) UserSignUp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadCourseImage operation middleware
func (siw *ServerInterfaceWrapper) UploadCourseImage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadCourseImage(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateCourse operation middleware
func (siw *ServerInterfaceWrapper) CreateCourse(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCourse(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteCourse operation middleware
func (siw *ServerInterfaceWrapper) DeleteCourse(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCourse(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetCourseById operation middleware
func (siw *ServerInterfaceWrapper) GetCourseById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCourseById(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateCourse operation middleware
func (siw *ServerInterfaceWrapper) UpdateCourse(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCourse(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetCourses operation middleware
func (siw *ServerInterfaceWrapper) GetCourses(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCoursesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "orderBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "orderBy", r.URL.Query(), &params.OrderBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderBy", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCourses(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPlaylists operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylists(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlaylistsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "author" -------------

	err = runtime.BindQueryParameter("form", true, false, "author", r.URL.Query(), &params.Author)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author", Err: err})
		return
	}

	// ------------- Optional query parameter "createdAt" -------------

	err = runtime.BindQueryParameter("form", true, false, "createdAt", r.URL.Query(), &params.CreatedAt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdAt", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "title" -------------

	err = runtime.BindQueryParameter("form", true, false, "title", r.URL.Query(), &params.Title)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "title", Err: err})
		return
	}

	// ------------- Optional query parameter "orderBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "orderBy", r.URL.Query(), &params.OrderBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderBy", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylists(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) CreatePlaylist(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlaylist(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeletePlaylist operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylist(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePlaylist(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPlaylistById operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylistById(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlaylist(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePlaylist(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UploadPlaylistImage operation middleware
func (siw *ServerInterfaceWrapper) UploadPlaylistImage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "playlist_id" -------------
	var playlistId int

	err = runtime.BindStyledParameterWithOptions("simple", "playlist_id", chi.URLParam(r, "playlist_id"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlist_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadPlaylistImage(w, r, playlistId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// Pong operation middleware
func (siw *ServerInterfaceWrapper) Pong(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Pong(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserById(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "role" -------------

	err = runtime.BindQueryParameter("form", true, false, "role", r.URL.Query(), &params.Role)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "role", Err: err})
		return
	}

	// ------------- Optional query parameter "orderBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "orderBy", r.URL.Query(), &params.OrderBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderBy", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UploadUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) UploadUserAvatar(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadUserAvatar(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UserSignIn operation middleware
func (siw *ServerInterfaceWrapper) UserSignIn(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserSignIn(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UserSignUp operation middleware
func (siw *ServerInterfaceWrapper) UserSignUp(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserSignUp(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/course/image/{user_id}", wrapper.UploadCourseImage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/course/new", wrapper.CreateCourse)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/course/{id}", wrapper.DeleteCourse)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/course/{id}", wrapper.GetCourseById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/course/{id}", wrapper.UpdateCourse)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses", wrapper.GetCourses)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/playlists", wrapper.GetPlaylists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists/new", wrapper.CreatePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/playlists/{id}", wrapper.DeletePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/playlists/{id}", wrapper.GetPlaylistById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/playlists/{id}", wrapper.UpdatePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists/{playlist_id}/image", wrapper.UploadPlaylistImage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pong", wrapper.Pong)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/user/{id}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user/{id}", wrapper.GetUserById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/user/{id}", wrapper.UpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/avatar", wrapper.UploadUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/sign_in", wrapper.UserSignIn)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/sign_up", wrapper.UserSignUp)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa72rcOhZ/FaPdj9PxJLl3oQOBbdNuN5dyKYR8KiEo9smMii35SnLSuWUgTWD3y7L3",
	"DXbZNwjdhuambfoK8htdJNljz1iecdKkkGkgEI+tP+fP7xz9dKQ3KGBxwihQKVD/DRLBEGJsHjdYygXo",
	"p4SzBLgkYN7jVA4Z3yWh/gGvcZxEgPorHSRHCaA+IlTCADgad1CAJQwYH+mWREJs+ufNhOSEDnSr/AXm",
	"HI9MLzPxLonxAGanQSReWVvBIlxd+RUL1KmPFnDAEsJHUvfbZzzGEvVRiCU8kCQGV5cQRMBJIgmj05P9",
	"hA+wqwPQ8AmW0H6GWWP1OmVHQuXaKnKZL+EkgKmODx92Hz6cNKVpvGdbCom5vJpIQmKZGocATWPUf4kS",
	"4IJRHKEOCiImIEQdBK8Tws0TS4AibasIJIRoxzGkJDKCdhZMk/BqXipxwvZeQSD1IBahYgpdf+awj/ro",
	"T36Jaz8HtZ8j2gG5TSqBUxxtAT8gATzlnPE68gMWzqhX9PME8APgHpiOLl/GIAQetOru1PVFhEcREbJ1",
	"PPacAWkttktC4YrJSstaUH6DsKqnlGqQ/OUHp2GvmSZuGascfklN4PRf5lN1Ko7amePg9nCeQMLhrm0B",
	"DgDjAyxxDSpoZXXthx+v7EGPCE8OwdsDIZ1JMsYkmu72ig3pX837bsDiayTKBgxEbEBmJJRDMDZwzJFg",
	"IQ4Zb2sEzixQJj4p8uVzTHRGxGFs/sdgsrF+oNJmAcDBELg7V045bAYxVp/ChLkInYr7agDqoNexMTbF",
	"sX6dat3HORC2yIBu0jocruUhh61/YkN6JUO3S++F6NvJtxedMkn2SYBr0Jc8hUn7PcYiwPSGdDWKTYUc",
	"ek6E9Ni+p93pTVzdKjsY9NeBpgPztV11nrDAMeXfCA09lkovZhw8vKcftw7xYGCwnfII9dFQyqTv+8K+",
	"7hJmQpfuM7tKUokDkyzL1qLv+7Ibg7+hbQCbP2/U8gtS/8neqs/qUr1Tn9Vp9pun3qtLdZGdqE/qTH3O",
	"jtVp9g91rj98UZeFUF3UQREJgFqumuP/UaJDz1vt9maFPjw87GLztcv4wM+7Cv/55sbTn7eePljt9rpD",
	"GUeVRQLlU2mBPprpsyN1qc7UhZbJs7Ti7+ke6qAD4MJqs9LtdXt6EE2ccEJQH611e12NhwTLobG8b9dj",
	"36xh/hvt5V0Sjg3cmV3rNegNCjdD1EfbScRwaCfc1J3MaBzHIA1+Xs56s/LL4zDAPCR04JkumnPqcDDi",
	"oE41c+gUU81IFvQWWS66MN6xrUHIxywcFSgAalSI00iSBHPp61T+IMQSl1sNsyyFIdES4uhFNcjrcTKu",
	"YcZYzkt55OVaTAtt8qpIGM1p4mqvNyMcTpIoj3P/lbDBvlCyck3aIxTzEWpO8M2ib6VBAELsp5E3cbLu",
	"+OMVZZyXBJy81iFLMxEVaRxrDQvseSSHncQDDbiCUqId3boANIXDZhBvGCqZk/GvdFAbun/3TW8t5gWF",
	"yeba/k2eQexOrW7+J+b9xPw3nD4WZI559QKbRe7BsAAM1n/zwNBBA3DE3TOQ1gqPR5vhvefvnuefgczd",
	"7u2NPGNvl/OT1MkcQnwf9Xd59Q1bLwHGjPNTgFiEAfVfdZodqVPNvbPj7KjkvupSfcxOsn9qTm7Z+KUh",
	"xGfqvTpTH81rzeLPPHWh26pz3TZ7mx2rd+rS04Q+O8reap5fgOmXFAyJytEUkZjofY4DQPbb+krPUQcY",
	"d25eif8biWtqnE6p4ZkvuvMHj+3vC5ANik0+ujSzH79WNS1RdpQdq3OzR3mnLtT5tLBm85SdqAt1qj6o",
	"01zRT9lJYZZ/e7qLGVddqvfZiXPQJhV5CPzxqElH+3XdlsL6WiXH/vj2M4JYhpRgigM4irxgEtLurJBU",
	"S4tNeaGsPy5nZnANZ2E4NV7bY6qmIcs6uVvKyff11d7qyoOe/nOViNyj54c2ToHLOWyr9ckhzjVVKerW",
	"LjXMt3V3xfw+Wd1UtihjcpnSVVLJNEXCKt/NpKw2pYTJQci8KtTXe8GleL4zp3A4UevGi1DXle2OVjkq",
	"dlyMjnbFjgpAZpa2O7SXaWvqO1rPWOD2zkLi4q5q3CEHL1MsPwM58WitWDHt1znliqWI22Vya16FuFqK",
	"Lh53STi2R12LDrgKk93SEVdFoG95zDXLHGsesOf7y3Sa1XiA5EnWCkWMDho3rS/0x680yUKftNArsXJM",
	"dNA/rfipAN6SouSXVb6Tuqy9nLA03CXNbxrlCEjNZY55nEXr/32dwiyLxzWxMbdxZklN6fQ5hOY+yu8w",
	"62mI8iLRz62u2vtd309lNb+x6CpTLrg9WVyanNyj3OlURNHjrhd9WtQ17+uQNxXIy1WDTPN4bAxm35Lx",
	"RTsVbZlHtuX93mDJbrrhwq/NIBFkQHftneIGlJTXr2+nOF2ZwGV5MqAeoaY+nS9f3642vSzL/yOTd8mv",
	"ixmAxUOaLMbDdnLLeNhOGvGQJvd4uIFziiYw6Lams6V403fgE5BCMg5r3fLyvI8T4h+sIb2E56PViMv/",
	"1Bd1brjIheF+5r6JuQ6vfveytyVZ0dzmvHIcXVx36Fx9yC+GWP5u2KRmkjNDl7Wa6w2uWdO/1AdDjU6z",
	"Y81js9+mp7A2rQ+fV1wKQfSv8c74jwAAAP//UiaAz8w6AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
